---
component: 'test'
deployment_identifier: "%{hiera('seed')}"

organization_id: "602e67f467852d083d43a50f"

region: 'eu-west-1'
availability_zones:
  - "eu-west-1a"
  - "eu-west-1b"

vpc_cidr: "10.1.0.0/16"

allow_cidrs:
  - "10.0.0.0/8"
