---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"

vars:
  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  region: "%{hiera('region')}"

  allow_cidrs: "%{hiera('allow_cidrs')}"
