---
source_directory: "spec/infra/prerequisites"
state_file: "%{hiera('project_directory')}/state/prerequisites.tfstate"
vars:
  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  organization_id: "%{hiera('organization_id')}"

  region: "%{hiera('region')}"
  availability_zones: "%{hiera('availability_zones')}"

  vpc_cidr: "%{hiera('vpc_cidr')}"
