---
configuration_directory: "%{cwd}/spec/unit/infra/prerequisites"
state_file: "%{cwd}/state/prerequisites.tfstate"
vars:
  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  region: "%{hiera('region')}"
  availability_zones: "%{hiera('availability_zones')}"

  vpc_cidr: "%{hiera('vpc_cidr')}"

  organization_id: "%{hiera('organization_id')}"
